# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCOOTER' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SCOOTER
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'NKVPhonePicker'    

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  
  pod 'SideMenu'
  pod 'IQKeyboardManagerSwift'
  pod 'PinCodeTextField'

  pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  
  pod 'Stripe'
  pod 'Repeat'
  pod 'HideShowPasswordTextField', :git => 'https://github.com/Guidebook/HideShowPasswordTextField'

#  target 'SCOOTERTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'SCOOTERUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
